import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {runInNewContext} from 'node:vm';
import {transformSync} from 'esbuild';
function load(file,extra={}){const module={exports:{}};runInNewContext(transformSync(readFileSync(new URL('../'+file,import.meta.url),'utf8'),{loader:'ts',format:'cjs'}).code,{module,exports:module.exports,URL,URLSearchParams,AbortSignal,...extra});return module.exports}
test('original URL hands off only the button, preserving campaign and visit',()=>{const m=load('src/lib/lineEntry.ts',{window:{location:{search:'?utm_source=facebook&utm_medium=promotion&fbclid=actualClickIdentifier12345'}}});const u=new URL(m.trackedLineEntryUrl('ce131f9e-c506-41d2-b5d7-e4524e40d39a'));assert.equal(u.origin,'https://massenlighten-platform.massenlighten-company.workers.dev');assert.equal(u.pathname,'/r/line-direct');assert.equal(u.searchParams.get('utm_source'),'facebook');assert.equal(u.searchParams.get('fbclid'),'actualClickIdentifier12345');assert.equal(u.searchParams.get('entry_visit'),'ce131f9e-c506-41d2-b5d7-e4524e40d39a')});
test('separate ad clicks cannot share a cached visit',async()=>{const keys=[];const window={location:{search:'?fbclid=clickOne',origin:'https://massenlight.github.io',pathname:'/richsong112/'},sessionStorage:{getItem:k=>{keys.push(k);return ''},setItem:()=>{}}};const env={window,document:{referrer:''},fetch:async()=>({ok:true,json:async()=>({entryVisit:'ce131f9e-c506-41d2-b5d7-e4524e40d39a'})})};await load('src/lib/directLandingTracking.ts',env).ensureDirectLandingVisit();window.location.search='?fbclid=clickTwo';await load('src/lib/directLandingTracking.ts',env).ensureDirectLandingVisit();assert.notEqual(keys[0],keys[1])});
test('preview creates no tracking request',async()=>{let calls=0;const m=load('src/lib/directLandingTracking.ts',{window:{location:{search:'?preview=1'}},fetch:()=>{calls++;throw Error()}});assert.equal(await m.ensureDirectLandingVisit(),'');assert.equal(calls,0)});
test('tracking network failure permits retry',async()=>{let calls=0;const m=load('src/lib/directLandingTracking.ts',{window:{location:{search:'',origin:'https://massenlight.github.io',pathname:'/richsong112/'},sessionStorage:{getItem:()=>'',setItem:()=>{}}},document:{referrer:''},fetch:async()=>{calls++;throw Error('network')}});await m.ensureDirectLandingVisit();await m.ensureDirectLandingVisit();assert.equal(calls,2)});
test('one shared pixel and no false registration conversion on landing',()=>{const html=readFileSync(new URL('../index.html',import.meta.url),'utf8'),app=readFileSync(new URL('../src/App.tsx',import.meta.url),'utf8');assert.equal(html.split('shifeng-pixel.js').length-1,1);assert.ok(!html.includes('GTM-KSB7777L'));assert.ok(app.includes('shifengPixel?.lead()'));assert.ok(!app.includes('CompleteRegistration'));assert.ok(!html.includes('location.replace'))});
